export const metadata = {
  title: 'Direccion de  Pre-Facultad',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <h1>Comedor</h1>
        {children}
      </body>
    </html>
  )
}
